# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'graffiti' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for graffiti
	pod 'jot'
end
