# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'graffiti' do
 	pod 'jot'
end

target 'graffitiTests' do

end

target 'graffitiUITests' do

end

